//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lamb_Ji_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club_Lutteur
    {
        public int Club_LutteurID { get; set; }
        public int LutteurID { get; set; }
        public int ClubID { get; set; }
        public System.DateTime Date_Entree { get; set; }
        public Nullable<System.DateTime> Date_Sortie { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Lutteur Lutteur { get; set; }
    }
}
