//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lamb_Ji_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CNGLUTTEDBEntities : DbContext
    {
        public CNGLUTTEDBEntities()
            : base("name=CNGLUTTEDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Affiche> Affiches { get; set; }
        public virtual DbSet<Arbitre> Arbitres { get; set; }
        public virtual DbSet<AvisAffiche> AvisAffiches { get; set; }
        public virtual DbSet<Categorie> Categories { get; set; }
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<Club_Lutteur> Club_Lutteur { get; set; }
        public virtual DbSet<Combat> Combats { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Licence> Licences { get; set; }
        public virtual DbSet<Lutteur> Lutteurs { get; set; }
        public virtual DbSet<Stade> Stades { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TypeLutte> TypeLuttes { get; set; }
    
        public virtual ObjectResult<Affichage_Complet_Lutteur_Result> Affichage_Complet_Lutteur()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Affichage_Complet_Lutteur_Result>("Affichage_Complet_Lutteur");
        }
    }
}
